"""users table

Revision ID: 3470c7c964f1
Revises: 
Create Date: 2021-10-28 15:59:22.350932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3470c7c964f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('detalles', sa.String(), nullable=True),
    sa.Column('cantidad_calificaciones', sa.Integer(), nullable=True),
    sa.Column('calificacionPromedio', sa.Float(), nullable=True),
    sa.Column('cantidad_comentarios', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habitacion_calificacionPromedio'), 'habitacion', ['calificacionPromedio'], unique=False)
    op.create_index(op.f('ix_habitacion_detalles'), 'habitacion', ['detalles'], unique=False)
    op.create_index(op.f('ix_habitacion_disponible'), 'habitacion', ['disponible'], unique=False)
    op.create_index(op.f('ix_habitacion_nombre'), 'habitacion', ['nombre'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('rol', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_nombre'), 'usuario', ['nombre'], unique=True)
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_habitacion', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.String(), nullable=True),
    sa.Column('fecha_fin', sa.String(), nullable=True),
    sa.Column('calificacion_reserva', sa.Integer(), nullable=True),
    sa.Column('precio_total', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserva_calificacion_reserva'), 'reserva', ['calificacion_reserva'], unique=False)
    op.create_index(op.f('ix_reserva_estado'), 'reserva', ['estado'], unique=False)
    op.create_index(op.f('ix_reserva_fecha_fin'), 'reserva', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_reserva_fecha_inicio'), 'reserva', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_reserva_precio_total'), 'reserva', ['precio_total'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserva_precio_total'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_fecha_inicio'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_fecha_fin'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_estado'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_calificacion_reserva'), table_name='reserva')
    op.drop_table('reserva')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nombre'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_habitacion_nombre'), table_name='habitacion')
    op.drop_index(op.f('ix_habitacion_disponible'), table_name='habitacion')
    op.drop_index(op.f('ix_habitacion_detalles'), table_name='habitacion')
    op.drop_index(op.f('ix_habitacion_calificacionPromedio'), table_name='habitacion')
    op.drop_table('habitacion')
    # ### end Alembic commands ###
