"""users table

Revision ID: 564692435947
Revises: 
Create Date: 2021-10-29 17:16:38.027438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564692435947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('detalles', sa.String(), nullable=True),
    sa.Column('cantidad_calificaciones', sa.Integer(), nullable=True),
    sa.Column('calificacionPromedio', sa.Float(), nullable=True),
    sa.Column('cantidad_comentarios', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_habitacion_calificacionPromedio'), 'habitacion', ['calificacionPromedio'], unique=False)
    op.create_index(op.f('ix_habitacion_detalles'), 'habitacion', ['detalles'], unique=False)
    op.create_index(op.f('ix_habitacion_disponible'), 'habitacion', ['disponible'], unique=False)
    op.create_index(op.f('ix_habitacion_nombre'), 'habitacion', ['nombre'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('rol', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_nombre'), 'usuario', ['nombre'], unique=False)
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user')
    )
    op.create_index(op.f('ix_administrador_id'), 'administrador', ['id'], unique=True)
    op.create_index(op.f('ix_administrador_rol'), 'administrador', ['rol'], unique=False)
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_habitacion', sa.Integer(), nullable=True),
    sa.Column('nombre_usuario', sa.String(length=64), nullable=True),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentario_comentario'), 'comentario', ['comentario'], unique=False)
    op.create_index(op.f('ix_comentario_nombre_usuario'), 'comentario', ['nombre_usuario'], unique=False)
    op.create_table('reserva_habitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_habitacion', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.String(), nullable=True),
    sa.Column('fecha_fin', sa.String(), nullable=True),
    sa.Column('calificacion_reserva', sa.Integer(), nullable=True),
    sa.Column('precio_total', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id_habitacion'], ['habitacion.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserva_habitacion_calificacion_reserva'), 'reserva_habitacion', ['calificacion_reserva'], unique=False)
    op.create_index(op.f('ix_reserva_habitacion_estado'), 'reserva_habitacion', ['estado'], unique=False)
    op.create_index(op.f('ix_reserva_habitacion_fecha_fin'), 'reserva_habitacion', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_reserva_habitacion_fecha_inicio'), 'reserva_habitacion', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_reserva_habitacion_precio_total'), 'reserva_habitacion', ['precio_total'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserva_habitacion_precio_total'), table_name='reserva_habitacion')
    op.drop_index(op.f('ix_reserva_habitacion_fecha_inicio'), table_name='reserva_habitacion')
    op.drop_index(op.f('ix_reserva_habitacion_fecha_fin'), table_name='reserva_habitacion')
    op.drop_index(op.f('ix_reserva_habitacion_estado'), table_name='reserva_habitacion')
    op.drop_index(op.f('ix_reserva_habitacion_calificacion_reserva'), table_name='reserva_habitacion')
    op.drop_table('reserva_habitacion')
    op.drop_index(op.f('ix_comentario_nombre_usuario'), table_name='comentario')
    op.drop_index(op.f('ix_comentario_comentario'), table_name='comentario')
    op.drop_table('comentario')
    op.drop_index(op.f('ix_administrador_rol'), table_name='administrador')
    op.drop_index(op.f('ix_administrador_id'), table_name='administrador')
    op.drop_table('administrador')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nombre'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_habitacion_nombre'), table_name='habitacion')
    op.drop_index(op.f('ix_habitacion_disponible'), table_name='habitacion')
    op.drop_index(op.f('ix_habitacion_detalles'), table_name='habitacion')
    op.drop_index(op.f('ix_habitacion_calificacionPromedio'), table_name='habitacion')
    op.drop_table('habitacion')
    # ### end Alembic commands ###
